POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuaWtldGgiLCJpZCI6IjYyYjQyODRhYTViZGE3MWI3MGUwMTZlZiIsImlhdCI6MTY1NTk5NTQyOSwiZXhwIjoxNjU1OTk5MDI5fQ.biWVN7R_pK1cC-24Q4kRsosJ0i-5DiaMfwxPsGyRDYY

{
  "title": "Test Title X1",
  "author": "Test User sadsa",
  "url": "https://www.testurldasd.com"
}