POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuaWtldGgiLCJpZCI6IjYyYjQyODRhYTViZGE3MWI3MGUwMTZlZiIsImlhdCI6MTY1NTk3NjY4MSwiZXhwIjoxNjU1OTgwMjgxfQ.-02HH8GoPl3gCCgdowlwZ7LQDe70JV_N8ewdSps6DeI

{
  "title": "Test Title X",
  "author": "Test User ani",
  "url": "https://www.testurlx.com"
}